# Site settings
title: Sydney Uni Maker Club
email: greetings@sydneyunimaker.club
description: > # this means to ignore newlines until "baseurl:"
  We're a student run society thats aimed at facilitating makerspaces and a 
  social hub for people to get inspired for starting their own side projects. 
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.sydneyunimaker.club" # the base hostname & protocol for your site
twitter_username: SUMakerClub
github_username:  sydneyunimakerclub
facebook_page: groups/sydneyunimakerclub
# Build settings
markdown: kramdown
